#!/bin/bash
sudo iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 80 -j REDIRECT --to-port 8080

npm install forever -g
npm install httpdispatcher

forever stopall

forever start server/server.json